#!/usr/bin/perl

# ./gip_extended_search ... | cut -f 1 | xargs -L 1 ./get_iplayer --pvr-queue --type tv --pid

use HTTP::Tiny;

my @pids=();
foreach my $url (@ARGV) {
    my $response = HTTP::Tiny->new->get($url);
    die "Failed to fetch $url: $response->{status} $response->{reason}\n" unless $response->{success};

    my $pages = ($response->{content} =~ /data-page-total="(\d+)"/) ? $1 : 1;
    my $page = 1;
    while ($page <= $pages) {
	$response = HTTP::Tiny->new->get("$url?page=$page");
	die "Failed to fetch $url?page=$page: $response->{status} $response->{reason}\n" unless $response->{success};

	my $content = $response->{content};
	while ($content =~ m/data-ip-id="([a-zA-Z0-9]+)"/g) {
	    my $pid = $1;
	    # Note: the title search regexp match below uses a different variable for the page content so that
	    # the global match position for the $content variable is not lost
	    my $title = ($response->{content} =~ m!href="[^"]*/$pid/[^"]*"[^>]+title="([^"]*)"!) ? $1 : '';
	    push @pids, $pid;
	    print "$pid\t$title\n";
	}

	$page++;
    };

}
